name: cihan_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  eva_icons_flutter: ^3.1.0
  flutter_swiper_null_safety: ^1.0.2
  chip_list: ^2.4.3+8
  firebase_core: ^2.14.0
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^4.0.1
  twitter_login: ^4.4.1
  firebase_auth: any
  firebase_ui_auth: ^1.5.0
  desktop_webview_auth: ^0.0.12
  http: any
  cloud_firestore: ^4.8.1
  firebase_ui_oauth_google: any
  firebase_ui_oauth_facebook: any
  firebase_ui_oauth_twitter: ^1.2.3
  firebase_phone_auth_handler: any
  flutter_riverpod: ^2.3.6
  firebase_app_check: ^0.1.4+3
  intl: any
  cached_network_image: ^3.2.3
  flutter_html: ^3.0.0-beta.2
  chips_choice: ^3.0.0
  flutter_timer_countdown: ^1.0.5
  rxdart: ^0.27.7
  fluttertoast: ^8.2.2
  modal_progress_hud_nsn: ^0.4.0
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.1
  flutter_image_compress: ^2.0.3
  path_provider: ^2.0.15
  firebase_storage: ^11.2.5
  flutter_typeahead: ^4.6.2
  firebase_messaging: ^14.6.5
  flutter_signin_button: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf


