name: cihan_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.5.6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  eva_icons_flutter: ^3.1.0
  flutter_swiper_null_safety: ^1.0.2
  chip_list: ^2.4.3+8
  firebase_core: any
  google_sign_in: any
  flutter_facebook_auth: any
  twitter_login: any
  firebase_auth: any
  firebase_ui_auth: any
  http: any
  cloud_firestore: any
  firebase_ui_oauth_google: any
  firebase_ui_oauth_facebook: any
  firebase_ui_oauth_twitter: any
  firebase_phone_auth_handler: any
  flutter_riverpod: any
  firebase_app_check: any
  intl: any
  cached_network_image: any
  flutter_html: ^3.0.0-beta.2
  chips_choice: any
  flutter_timer_countdown: any
  rxdart: any
  fluttertoast: any
  modal_progress_hud_nsn: any
  hooks_riverpod: any
  image_picker: any
  flutter_image_compress: any
  path_provider: any
  flutter_typeahead: ^4.8.0
  firebase_messaging: any
  flutter_signin_button: any
  google_mobile_ads: any
  shared_preferences: any
  share_plus: any
  firebase_dynamic_links: any
  shimmer: any
  flutter_native_splash: any
  connectivity_plus: ^4.0.0
  flutter_offline: any
  flutter_hooks: any
  overlay_support: any
  device_preview: any
 #firebase_storage: ^11.2.8


dependency_overrides:
  firebase_ui_shared: 1.4.1











dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_lint: ^2.3.7


flutter_native_splash:
  android: true
  ios: true
  image: "assets/images/splashlogo.png"
  color: "#FFFFFF"
  android_12:
    image: "assets/playstore-icon.png"
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/playstore-icon.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/playstore-icon.png
    - assets/splashlogo.png
    - assets/dialogueTicket.png


  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf


